#ifndef YMX2D_FUNCTION_CLASS_ENUM_H
#define YMX2D_FUNCTION_CLASS_ENUM_H

enum YMX2D_API YMXGAME_ATTRIBUTE
{
	GAME_WINDOW_TITLE,
	GAME_ICON_RESOURCE,
	GAME_WINDOW_WIDTH,
	GAME_WINDOW_HEIGHT,
	GAME_PARTICLE_ACCELERATE,
	GAME_FULL_SCREEN,
	GAME_UPDATE_FPS,
	GAME_LOAD_LUACOMPONENTS,
	GAME_CURSOR_RESOURCE,
	GAME_SHOW_CURSOR,
	GAME_LOG_FILE,
	GAME_LOG_ERROR
};

enum YMX2D_API PARTICLESYSTEM_TYPE
{
	PAR_TYPE_SNOW = 0,
	PAR_TYPE_FLAME = 1,
	PAR_TYPE_EXPLODE = 2,
	PAR_TYPE_COMET = 3
};

typedef enum YmxBordary
{
	LEFT = 0, RIGHT, BOTTOM, TOP
} YMXBORDARY;


enum YMX2D_API YMXFONT_ATTRIBUTE
{
	FONT_BUFFER_COUNT = 0,	//count of strings in buffer
	FONT_MULTILINE,		    //Support multiple line when enter \n
	FONT_AUTO_NEWLINE,	    //Automatically change new line
	FONT_MAX_CHAR_COUNT     //control m_MaxCharCount
};

enum YMX2D_API YMXCOMPONENT_ATTRIBUTE
{
	COMPONENT_REQUIRE_CLIP = 0,
	COMPONENT_VISIBLE,
	COMPONENT_ENABLE,
	COMPONENT_BACKGROUND_TRANSPARENT
};

// Game Component Messages
#define GCM_SETVISIBLE -1
#define GCM_SETENABLED -2
#define GCM_BUTTON_MOUSEOVER -3
#define GCM_BUTTON_MOUSEOUT -4
#define GCM_BUTTON_CLICK -5
#define GCM_LIST_MOUSEOVER -6
#define GCM_LIST_MOUSEOUT -7
#define GCM_LIST_CLICK -8
#define GCM_EDITTEXT_CONFIRM -9
#define GCM_EDITTEXT_CHANGE -10

// Game Message Flags
#define GMF_CAPTURE 0x00
#define GMF_BUBBLE  0x01
#define GMF_THROWABLE 0x10000000

#define ROOT_COMPONENT_ID -999
#define ROOT_COMPONENT_NAME "ymxcomponentroot"

#define VK_0 0x30
#define VK_1 0x31 
#define VK_2 0x32
#define VK_3 0x33
#define VK_4 0x34
#define VK_5 0x35 
#define VK_6 0x36
#define VK_7 0x37
#define VK_8 0x38
#define VK_9 0x39

#endif

